dist: trusty
language: php
sudo: required

php:
  - 7.1
  - 7.2
  - 7.3

services:
  - memcached
  - redis-server

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - chmod -R o+w vendor/orchestra

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - bliz48rus@gmail.com
    on_success: never
    on_failure: always